import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const animatedLineChartConfig: ComponentConfig = {
  componentName: "AnimatedLineChart",
  importPath: "@/components/snap-cn/animated-line-chart",
  controls: {
    title: {
      type: "text",
      default: "Weekly active users",
      label: "Title",
    },
    showValue: { type: "boolean", default: true, label: "Show live value" },
    width: {
      type: "number",
      default: 880,
      min: 480,
      max: 1200,
      step: 10,
      label: "Chart width",
    },
    height: {
      type: "number",
      default: 400,
      min: 240,
      max: 620,
      step: 10,
      label: "Chart height",
    },
    strokeColor: { type: "color", default: "#266DF0", label: "Stroke color" },
    strokeWidth: {
      type: "number",
      default: 3,
      min: 1,
      max: 10,
      step: 1,
      label: "Stroke width",
    },
    gridColor: { type: "color", default: "#E4E7EC", label: "Grid color" },
    labelColor: { type: "color", default: "#667085", label: "Label color" },
    valueColor: { type: "color", default: "#101828", label: "Value color" },
    showDot: { type: "boolean", default: true, label: "Show leading dot" },
    showCard: { type: "boolean", default: true, label: "Card surface" },
    cardColor: { type: "color", default: "#FFFFFF", label: "Card color" },
  },
  durationInFrames: 120,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
