import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const counterConfig: ComponentConfig = {
  componentName: "Counter",
  importPath: "@/components/snap-cn/counter",
  controls: {
    from: {
      type: "number-input",
      default: 0,
      min: 0,
      max: 10000000,
      step: 1,
      label: "From",
    },
    to: {
      type: "number-input",
      default: 128400,
      min: 0,
      max: 10000000,
      step: 1,
      label: "To",
    },
    mode: {
      type: "select",
      default: "odometer",
      options: ["rolling", "odometer", "slot"],
      label: "Mode",
    },
    prefix: { type: "text", default: "$", label: "Prefix" },
    suffix: { type: "text", default: "", label: "Suffix" },
    separator: {
      type: "select",
      default: "comma",
      options: ["comma", "space", "none"],
      label: "Separator",
    },
    countPortion: {
      type: "number",
      default: 0.8,
      min: 0.3,
      max: 1,
      step: 0.05,
      label: "Count portion",
    },
    columnStagger: {
      type: "number",
      default: 4,
      min: 0,
      max: 12,
      step: 1,
      label: "Column stagger (slot)",
    },
    fontSize: {
      type: "number",
      default: 120,
      min: 24,
      max: 280,
      step: 4,
      label: "Font size",
    },
    color: { type: "color", default: "#101828", label: "Color" },
    fontWeight: {
      type: "select",
      default: "800",
      options: ["400", "500", "600", "700", "800"],
      label: "Font weight",
    },
  },
  durationInFrames: 150,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
