import { type ComponentConfig, FPS, H, W } from "@/lib/customizer-config";

export const progressRingConfig: ComponentConfig = {
  componentName: "ProgressRing",
  importPath: "@/components/snap-cn/progress-ring",
  controls: {
    value: {
      type: "number",
      default: 87,
      min: 0,
      max: 100,
      step: 1,
      label: "Value (%)",
    },
    variant: {
      type: "select",
      default: "ring",
      options: ["ring", "bar"],
      label: "Variant",
    },
    thickness: {
      type: "number",
      default: 10,
      min: 2,
      max: 40,
      step: 1,
      label: "Thickness",
    },
    color: { type: "color", default: "#266DF0", label: "Fill color" },
    trackColor: { type: "color", default: "#E4E7EC", label: "Track color" },
    countUp: { type: "boolean", default: true, label: "Count up" },
    label: { type: "text", default: "", label: "Label override" },
    sublabel: {
      type: "text",
      default: "less manual entry",
      label: "Sublabel",
    },
    sublabelColor: {
      type: "color",
      default: "#667085",
      label: "Sublabel color",
    },
    size: {
      type: "number",
      default: 280,
      min: 120,
      max: 560,
      step: 10,
      label: "Size",
    },
    fontSize: {
      type: "number",
      default: 56,
      min: 16,
      max: 120,
      step: 1,
      label: "Readout size",
    },
    textColor: { type: "color", default: "#101828", label: "Readout color" },
    card: { type: "boolean", default: true, label: "White card" },
  },
  durationInFrames: 120,
  fps: FPS,
  compositionWidth: W,
  compositionHeight: H,
  previewBackdrop: { type: "color", value: "#FAFAFA" },
};
